### ISSUE TITLE
Example can not bulid on ios with Flutter 1.20.3

### ISSUE THREAD

**Issue by zxl777** [tanersener/flutter-ffmpeg#194] opened 2020-09-05 15:15 UTC
```
Launching lib/flutter_ffmpeg_example.dart on X-Sky in debug mode...
Upgrading project.pbxproj
Legacy build system detected, removing /Users/sky/Downloads/flutter-ffmpeg-master/example/ios/Runner.xcworkspace/xcshareddata/WorkspaceSettings.xcsettings
Project base configurations detected, removing.
Signing iOS app for device deployment using developer identity: "Apple Development: ....."
Running pod install...
Warning: Podfile is out of date
  This can cause issues if your application depends on plugins that do not support iOS.
  See https://flutter.dev/docs/development/packages-and-plugins/developing-packages#plugin-platforms for details.
  If you have local Podfile edits you would like to keep, see https://github.com/flutter/flutter/issues/45197 for instructions.
To regenerate the Podfile, run:
  rm ios/Podfile

```

Flutter 1.20.3

**Comment by tanersener** [comment] 2020-09-05 15:26
The title sounds like it is the duplicate of #175 or #185. But the issue doesn't include issue template fields. So, it is hard to say whether something is wrong or not.

**Comment by zxl777** [comment] 2020-09-06 13:19
Thanks. 
New Podfile, Worked!
```
# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_install_ios_plugin_pods(ios_application_path = nil)
  # defined_in_file is set by CocoaPods and is a Pathname to the Podfile.
  ios_application_path ||= File.dirname(defined_in_file.realpath) if self.respond_to?(:defined_in_file)
  raise 'Could not find iOS application path' unless ios_application_path

  # Prepare symlinks folder. We use symlinks to avoid having Podfile.lock
  # referring to absolute paths on developers' machines.

  symlink_dir = File.expand_path('.symlinks', ios_application_path)
  system('rm', '-rf', symlink_dir) # Avoid the complication of dependencies like FileUtils.

  symlink_plugins_dir = File.expand_path('plugins', symlink_dir)
  system('mkdir', '-p', symlink_plugins_dir)

  plugins_file = File.join(ios_application_path, '..', '.flutter-plugins-dependencies')
  plugin_pods = flutter_parse_plugins_file(plugins_file)
  plugin_pods.each do |plugin_hash|
    plugin_name = plugin_hash['name']
    plugin_path = plugin_hash['path']
    if (plugin_name && plugin_path)
      symlink = File.join(symlink_plugins_dir, plugin_name)
      File.symlink(plugin_path, symlink)

      if plugin_name == 'flutter_ffmpeg'
          pod 'flutter_ffmpeg/full', :path => File.join('.symlinks', 'plugins', plugin_name, 'ios')
      else
          pod plugin_name, :path => File.join('.symlinks', 'plugins', plugin_name, 'ios')
      end
    end
  end
end

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end

```

**Comment by umaqs** [comment] 2020-10-05 23:42
hows it working for you?
the defined method is named `flutter_install_ios_plugin_pods` but the one being called under target 'Runner' do is `flutter_install_all_ios_pods`. 
`pod install` would throw an error on that.

But when I rename the method to match the call, now there is another error saying

```
ios/Podfile:50
Invalid `Podfile` file: undefined method `flutter_parse_plugins_file' for #<Pod::Podfile:0x00007feaf7489a88>
Did you mean?  flutter_install_ios_plugin_pods.

```

@tanersener can you please tell me how to fix this?

Thanks

**Closed** 2020-12-12 02:05 UTC
Labels: duplicate, missing-issue-template, no-issue-activity
