### ISSUE TITLE
Will i get lawsuit if i use FFmpeg in my app ?

### ISSUE THREAD

**Issue by dubeyteja** [tanersener/flutter-ffmpeg#203] opened 2020-09-17 20:39 UTC
I'm using FFmpeg for mixing audio and video and adding watermarks. I don't know much about LGPL V3.0 licence i just want to know can i use it or i will get any issues legally ?

**Comment by tanersener** [comment] 2020-09-17 21:58
duplicate of #204

**Closed** 2020-11-24 01:42 UTC
Labels: duplicate, no-issue-activity
